#
#        ~_
#     ~_ )_)~_
#     )_))_))_)
#     _!__!__!_
#   ~~\t  Gemu/~~
#
#  File Name: makefile.pa_amb_tomaquet_rules
#  Purpose: Organize pa amb tomaquet rules
#  Creation Date: 24-01-21
#  Created By: Andrea Andreu Salvagnin
#

#PAT_FOLDER: path to PA_AMB_TOMAQUET folder
#FILE_OBJECTS_FOLDER: path to target file objects folder

$(PAT_GAME_O): $(PAT_GAME_CPP) $(PAT_GAME_H)
	$(CC) $(COMPILER_FLAGS) \
	-I$(PAT_SCENE) -I$(PAT_UTILS) -I$(PAT_INPUT) -I$(PAT_GRAPHICS) \
	$(LINKER_FLAGS) $< -o $@

$(PAT_SCREEN_O): $(PAT_SCREEN_CPP) $(PAT_SCREEN_H)
	$(CC) $(COMPILER_FLAGS) \
	$(LINKER_FLAGS) $< -o $@

$(PAT_SCENE_M_O): $(PAT_SCENE_M_CPP) $(PAT_SCENE_M_H)
	$(CC) $(COMPILER_FLAGS) \
	-I$(PAT_UTILS) -I$(PAT_INPUT) \
	$(LINKER_FLAGS) $< -o $@

$(PAT_SCENE_O): $(PAT_SCENE_H)
	$(CC) $(COMPILER_FLAGS) \
	-I$(PAT_INPUT) \
	$(LINKER_FLAGS) -x c++ $< -o $@

include $(PAT_FOLDER)/GameObjects/makefile.game_objects_rules

$(PAT_ANIMATION_M_O): $(PAT_ANIMATION_M_CPP) $(PAT_ANIMATION_M_H)
	$(CC) $(COMPILER_FLAGS) \
	-I$(PAT_UTILS) \
	$(LINKER_FLAGS) $< -o $@

$(PAT_ANIMATION_O): $(PAT_ANIMATION_CPP) $(PAT_ANIMATION_H)
	$(CC) $(COMPILER_FLAGS) \
	-I$(PAT_GRAPHICS) -I$(PAT_UTILS) \
	$(LINKER_FLAGS) $< -o $@

$(PAT_VECTOR2D_O): $(PAT_VECTOR2D_CPP) $(PAT_VECTOR2D_H)
	$(CC) $(COMPILER_FLAGS) \
	-I$(PAT_MATH) \
	$(LINKER_FLAGS) $< -o $@

$(PAT_MATH_UTILS_O): $(PAT_MATH_UTILS_CPP) $(PAT_MATH_UTILS_H)
	$(CC) $(COMPILER_FLAGS) \
	$(LINKER_FLAGS) $< -o $@

